<x-landing-layout>
    @include('pages.landing._partials._background')
    @include('pages.landing._partials._hero')
    @include('pages.landing._partials._services')
    @include('pages.landing._partials._welcome')
    @include('pages.landing._partials._about')
    @include('pages.landing._partials._whyme')
    @include('pages.landing._partials._reviews')
    @include('pages.landing._partials._faqs')
</x-landing-layout>
